Merge masterthesis into main  3 mpc (#168)
* call prospecter for pi, mpc, air conditoner

* implementation of the controller, use only small letters for file names, adding meaningful comments

* adding dynamic electricity price signal and FIT tarrifs for PV

* add weather data for new locations on southern Europe

* add test file for the air_conditioned_house

* adding path to price data

* getting signal from the MPC controller and modifying the pid part

* send yearly forecast of solar gains and other building parameters to the building model to be used for contructing the state space model

* sending battery efficiency to the model predictive controller

* send yearly forecast of heating by ressidents to the building

* send yearly forecast of annual pv generation to controller_mpc

* path correction and reading data of the added locations

* read prices from the input file

* correct typo error

* addinng casadi

* files renamed or location change

* adding control library

* adding control library

* adding casadi module

* trying to fix mypy errors

* trying to fix mypy errors

* removing implicit optional

* code quality improvement, add steps to obtain HSL solvers, future work

* code quality improvement and future work

* code quality

* Add minor comments

* Change unit type from 'CENTS_PER_KWH' to 'EUR_PER_KWH'

* Fix pylint warnings

* Fix pylint warnings

* Fix pylint warnings

* Fix pylint warnings

* Fix pylint warnings

* Fix Pylint issues: R1714

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0201

* Fix Pylint issues: W0612/W0613

* Fix Pylint issues: E1121

* Fix Pylint issues: R1710

* Fix Pylint issues: W0612

* Fix Mypy issues: 'Incompatible default for argument'

* Fix Mypy issues: 'Incompatible default for argument'

* Fix Mypy issues: 'type[Units]' has no attribute 'CENTS_PER_KWH'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'error: Value of type Optional[list[Any]] is not indexable'

* Fix Mypy issues: 'Incompatible default for argument'

* Fix Mypy issues: E1121

* Use config class instead of init function

* Use config class instead of init function

* Use config class instead of init function

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs - import ConfigBase

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs - incompatible type 'None'; expected 'list[float]'

* Use config class instead of init function - fix bugs - incompatible type 'None'; expected 'list[float]'

* Use config class instead of init function - fix bugs

* Use config class instead of init function - fix bugs

* Update 'generic_battery' for MPC use

---------

Co-authored-by: Marwa Alfouly <marwa.alfouly@tum.de>