Merge master thesis into main branch (Part 2: PID controller) (#157)
* call prospecter for pi, mpc, air conditoner

* implementation of the controller, use only small letters for file names, adding meaningful comments

* adding dynamic electricity price signal and FIT tarrifs for PV

* add weather data for new locations on southern Europe

* add test file for the air_conditioned_house

* adding path to price data

* getting signal from the MPC controller and modifying the pid part

* send yearly forecast of solar gains and other building parameters to the building model to be used for contructing the state space model

* sending battery efficiency to the model predictive controller

* send yearly forecast of heating by ressidents to the building

* send yearly forecast of annual pv generation to controller_mpc

* path correction and reading data of the added locations

* read prices from the input file

* correct typo error

* addinng casadi

* files renamed or location change

* adding control library

* adding control library

* adding casadi module

* trying to fix mypy errors

* trying to fix mypy errors

* removing implicit optional

* code quality improvement, add steps to obtain HSL solvers, future work

* code quality improvement and future work

* code quality

* Add minor comments

* Merge files from Alfoulys master thesis' branch into main branch

Renaming/sorting of weather data

* Merge files from Alfoulys master thesis' branch into main branch

Delete component 'air_conditioner' to include this component properly later without dependencies on other components

* Merge files from Alfoulys master thesis' branch into main branch

Weather data: Move acknowledgements for NSRDB weather data in main README file

* Merge files from Alfoulys master thesis' branch into main branch

Weather data: Include 2 missing data sets for Southern Europe for master thesis' simulations

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Add files to run simulations with 'air conditioner' and 'PID controller'

* Manual merge of 'air_conditioner' files with changes from Noah/Kathy (up to revision: 0af4bb2399f76e97f15d79fc033b2de054c83318) and Marwa (latest master thesis version)

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Add additional requirements

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Add additional entries to mypy files

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Modify default for argument 'my_simulation_repository' in component 'air_conditioner'

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Try to fix mypy issue for air_conditioner component

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Try to fix mypy fails by removing example 'air_conditioned_house.py'

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix pylint issues by removing trailing blank lines in the 'controller_pic' file

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix pylint issues by commenting out unused variables in the 'controller_pid' file

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix pylint issues in the 'controller_pid' file

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix pylint issues in the 'controller_pid' file

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Finally fix pylint issues in the 'controller_pid' file

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'controller_pid' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Incompatible default for argument 'my_simulation_repository')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('Unexpected keyword argument my_simulation_repository for build  [call-arg]')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Fix mypy issues in the 'air_conditioner' file ('error: Item None of Optional[SimRepository] has no attribute set_entry  [union-attr]')

* Merge files from Alfoulys master thesis' branch into main branch

PID Controller: Finally fixed mypy issues in the 'air_conditioner' file

---------

Co-authored-by: Marwa Alfouly <marwa.alfouly@tum.de>